---
- name: stop neutron_api containers
  ansible.builtin.systemd:
    name: tripleo_neutron_api
    state: stopped

- name: get neutron_server image url
  command: podman ps -a --filter "name=neutron_api" --format {% raw %}"{{.Image}}"{% endraw %}
  register: neutron_server_image
  when: ovn_central is defined

- name: check if TLS is enabled
  ansible.builtin.shell: grep -q '^\s*ovn_nb_connection=ssl:' /var/lib/config-data/puppet-generated/neutron/etc/neutron/plugins/ml2/ml2_conf.ini
  register: tls_enabled
  when: ovn_central is defined
  ignore_errors: yes

- name: get Internal TLS CA file
  ansible.builtin.shell: awk -F = '/^\s*ovn_nb_ca_cert/{ print $2 }' /var/lib/config-data/puppet-generated/neutron/etc/neutron/plugins/ml2/ml2_conf.ini
  register: internal_ca
  when:
    - ovn_central is defined
    - tls_enabled.rc == 0
  ignore_errors: yes

- name: sync neutron db with OVN db
  command: podman run --rm --name {{ ovn_db_sync_container }}
    -v /var/log/containers/neutron:/var/log/neutron
    -v /var/lib/config-data/puppet-generated/neutron/etc/neutron:/etc/neutron
    -v /etc/my.cnf.d/:/etc/my.cnf.d
    {% if tls_enabled.rc == 0 %}
    -v /etc/pki/tls/private/neutron_ovn.key:/etc/pki/tls/private/neutron_ovn.key
    -v /etc/pki/tls/certs/neutron_ovn.crt:/etc/pki/tls/certs/neutron_ovn.crt
    -v {{ internal_ca.stdout }}:{{ internal_ca.stdout }}
    {% endif %}
    --privileged=True --network host --user root
    {{ neutron_server_image.stdout }}
    neutron-ovn-db-sync-util --config-file /etc/neutron/neutron.conf
    --config-file /etc/neutron/plugins/ml2/ml2_conf.ini
    --log-file /var/log/neutron/neutron-db-sync.log
    --ovn-neutron_sync_mode {{ db_sync_mode }}
    --debug
  when: ovn_central is defined

- name: remove db-sync container
  command: podman rm -f {{ ovn_db_sync_container }}
  when: ovn_central is defined

- name: set migration mode to True
  ini_file:
    path: /var/lib/config-data/puppet-generated/neutron/etc/neutron/plugins/ml2/ml2_conf.ini
    section: ml2
    option: migration_mode
    value: True
  when: '{{ db_sync_mode == "repair" }}'

- name: set migration mode to False
  ini_file:
    path: /var/lib/config-data/puppet-generated/neutron/etc/neutron/plugins/ml2/ml2_conf.ini
    section: ml2
    option: migration_mode
    value: False
  when: '{{ db_sync_mode == "migrate" }}'

- name: start neutron_api containers
  ansible.builtin.systemd:
    name: tripleo_neutron_api
    state: started
