---
- name : Create temp file directory
  ansible.builtin.tempfile:
    state: directory
    prefix: ovn-migration.
  register: temp_dir

- name: Generate OVN activation script
  template:
    src: "deactivate-ovn.sh.j2"
    dest: "{{ temp_dir.path }}/deactivate-ovn.sh"
    mode: 0644

- name: Run OVN activation script
  shell: "sh {{ temp_dir.path }}/deactivate-ovn.sh 2>&1 > {{ temp_dir.path }}/deactivate-ovn.sh.log"

- name: Delete OVN activate script
  file:
    state: absent
    path: "{{ temp_dir.path }}/deactivate-ovn.sh"
