---
- name: "start and enable {{ service.name }} services and healthchecks"
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  become: yes
  when:
    - ansible_facts.services[item] is defined
    - ansible_facts.services[item]["state"] == "stopped"
    - ansible_facts.services[item]["status"] != "not-found"
  loop:
    - "{{ service.healthcheck_timer_file }}"
    - "{{ service.healthcheck_service_file }}"
    - "{{ service.service_file }}"
