---
- name: populate service facts
  service_facts:

    #- name: "stop and disable {{ item }}"
    #  systemd:
    #    name: "{{ item }}"
    #    state: stopped
    #    enabled: no
    #  when:
    #    - ansible_facts.services[item] is defined
    #    - ansible_facts.services[item]["status"] != "not-found"
    #  loop:
    #    - tripleo_ovn_controller.service
    #    - tripleo_ovn_metadata_agent.service

- include_tasks: deactivate-ovn.yml
  when: ovn_controller is defined

- name: Enabled ml2 ovs services and healthchecks
  include_tasks: enable-agents.yml
  loop: "{{ ml2_ovs_services }}"
  loop_control:
    loop_var: service
  when:
    - ansible_facts.services[service.service_file] is defined
    - ansible_facts.services[service.service_file]["status"] != "not-found"
