---
# If file is already deleted this won't fail
- name: delete ml2 ovs systemd service files
  file:
    path: "{{ systemd_service_file_dir }}/{{ item }}"
    state: absent
  loop:
    - "{{ service.service_file }}"
    - "{{ service.healthcheck_service_file }}"
    - "{{ service.healthcheck_timer_file }}"
  become: yes
