---
- name: populate service facts
  service_facts:

- include_tasks: activate-ovn.yml
  when: ovn_controller is defined

- include_tasks: cleanup-dataplane.yml
  when: ovn_controller is defined

- name: disable ml2 ovs services and healthchecks
  include_tasks: cleanup-agents.yml
  loop: "{{ ml2_ovs_services }}"
  loop_control:
    loop_var: service
  when: ansible_facts.services[service.service_file] is defined

- name: Reload systemctl daemons
  systemd:
    daemon_reload: yes
