---
- name: cleanup ml2/OVS agents services
  hosts: ovn-controllers
  roles:
    - cleanup

- name: migrate MySQL database to OVN
  vars:
    db_sync_mode: migrate
  hosts: neutron-api
  roles:
    - sync-dbs

- name: cleanup Neutron ml2/OVS resources
  hosts: localhost
  roles:
    - delete-neutron-resources
