---

- name: set migration mode to True for OVS agents
  hosts: ovn-controllers
  tasks:
    - name: change migration mode in OVS agents' configuration file to True
      ini_file:
        path: /var/lib/config-data/puppet-generated/neutron/etc/neutron/plugins/ml2/openvswitch_agent.ini
        section: ml2
        option: migration_mode
        value: True
      become: yes
      notify: 
        - restart OVS agents to pick the new configuration

  handlers:
    - name: restart OVS agents to pick the new configuration
      systemd:
        name: tripleo_neutron_ovs_agent
        state: restarted
      become: yes

- name: install OVN with the TripleO
  hosts: localhost
  roles:
    - tripleo-update
  become: false

- name: configure ovn-controller nodes
  hosts: ovn-controllers
  become: yes
  tasks:
    - name: backup bridge mappings
      shell: |
        ovn_bms=$(ovs-vsctl get open . external_ids:ovn-bridge-mappings | tr -d '"')
        if [ "x$ovn_bms" != "x" ]; then
            ovs-vsctl set open . external_ids:ovn-bridge-mappings-back="$ovn_bms" -- remove open . external_ids ovn-bridge-mappings
        fi

- name: sync dbs
  hosts: neutron-api
  roles:
    - sync-dbs
