---

- name : Create temp directory
  ansible.builtin.tempfile:
    state: directory
    prefix: ovn-migration.
  register: temp_dir

- name: Create ovn-extras generation script
  template:
    src: "generate-ovn-extras.sh.j2"
    dest: "{{ temp_dir.path }}/generate-ovn-extras.sh"
    mode: 0644

- name: Generate ovn-extras environment file
  shell: >
    set -o pipefail &&
    sh {{ temp_dir.path }}/generate-ovn-extras.sh
  args:
    creates: $HOME/ovn-extras.yaml

- name: Set to not clean orphaned services
  copy:
    src: disable-container-manage-clean-orphans.j2.yaml
    dest: /usr/share/openstack-tripleo-heat-templates/environments/disable-container-manage-clean-orphans.j2.yaml
  become: yes

- name: Updating the overcloud stack with OVN services
  shell: >
    set -o pipefail &&
    {{ overcloud_ovn_deploy_script }} 2>&1 > {{ overcloud_ovn_deploy_script }}.log
