- job:
    name: neutron-system-integration
    parent: devstack-minimal
    timeout: 7800
    required-projects:
      - opendev.org/openstack/devstack
      - openstack/neutron
      - openstack/requirements
    roles:
      - zuul: openstack/devstack
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^neutron/locale/.*$
      - ^releasenotes/.*$
    vars:
      OVN_BRANCH: v20.03.0
      # TODO(jlibosva): v2.13.0 is incompatible with kernel 4.15.0, sticking to commit hash until new v2.13 tag is created.
      OVS_BRANCH: 51e9479da62edb04a5be47a7655de75c299b9fa1

- job:
    name: neutron-functional
    parent: neutron-system-integration
    description: Run neutron functional tests
    pre-run: playbooks/configure_functional_job.yaml
    run: playbooks/run_functional_job.yaml
    post-run: playbooks/post_functional_job.yaml
    vars:
      devstack_services:
        # Ignore any default set by devstack. Emit a "disable_all_services".
        base: false
      devstack_localrc:
        INSTALL_TESTONLY_PACKAGES: true
        DATABASE_PASSWORD: stackdb
      tox_envlist: dsvm-functional
      tox_install_siblings: false
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/openstack/requirements/upper-constraints.txt'
      zuul_copy_output:
        # We need to copy directory with logs to have it in job artifacts also,
        # /opt/stack/logs is default logs directory defined in neutron's
        # tox.ini file
        '{{ devstack_base_dir }}/logs/dsvm-functional-logs': logs

- job:
    name: neutron-fullstack
    parent: neutron-functional
    vars:
      tox_envlist: dsvm-fullstack-gate
      zuul_copy_output:
        # We need to copy directory with logs to have it in job artifacts also,
        # /opt/stack/logs is default logs directory defined in neutron's
        # tox.ini file
        '{{ devstack_base_dir }}/logs/dsvm-fullstack-logs': logs

- job:
    name: neutron-fullstack-with-uwsgi
    parent: neutron-fullstack
    vars:
      devstack_localrc:
        NEUTRON_DEPLOY_MOD_WSGI: true
      # Because this job uses neutron defined tox env (defined in base job),
      # we need to set zuul_work_dir to neutron so that it can be used by
      # other projects. Currently devstack run this job. Not setting this
      # in base neutron-functional job as that is being used by neutron
      # stadium projects where they need to use stadium project as working dir.
      zuul_work_dir: src/opendev.org/openstack/neutron

- job:
    name: neutron-functional-with-uwsgi
    parent: neutron-functional
    vars:
      devstack_localrc:
        NEUTRON_DEPLOY_MOD_WSGI: true
      # Because this job uses neutron defined tox env (defined in base job),
      # we need to set zuul_work_dir to neutron so that it can be used by
      # other projects. Currently devstack run this job. Not setting this
      # in base neutron-functional job as that is being used by neutron
      # stadium projects where they need to use stadium project as working dir.
      zuul_work_dir: src/opendev.org/openstack/neutron

- job:
    name: neutron-george
    parent: neutron-system-integration
    description: This is George, experimental testing framework running multiple multi-node environments on a single host in parallel.
    pre-run: playbooks/george/configure_george_tests.yaml
    run: playbooks/george/run_george_run.yaml
    post-run: playbooks/george/post_run.yaml
    vars:
      tox_envlist: george
      tox_environment:
        OS_LOG_PATH: '/opt/stack/logs'
      zuul_copy_output:
        /tmp/george-logs: logs
